# -*- mode: cmake-mode; coding: utf-8-unix; *-

cmake_minimum_required(VERSION 3.25)
project(green VERSION 0.0.1)

set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable(green)
target_sources(green PUBLIC green.cpp
              )
target_compile_options(green PUBLIC -Wall -Wextra -Wpedantic
                                      -Wshadow -g -Og)